// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {IRiscZeroVerifier} from "risc0-ethereum/IRiscZeroVerifier.sol";

/// @title PolicyVerifier
/// @notice Bridges the sentinel `IVerifier` surface (returns bool) to a
///         canonical RISC Zero verifier (reverts on failure). Pins the
///         PolicyCompliance image ID so only proofs generated by that
///         specific guest ELF can authorize defense actions.
///
///         publicInputs order: [actionHash, policyHash, eventId].
///         Journal bytes = abi.encodePacked(publicInputs[0..3]) = 96 bytes,
///         matching the guest's `env::commit_slice` layout.
contract PolicyVerifier {
    IRiscZeroVerifier public immutable RISC0_VERIFIER;
    bytes32 public immutable IMAGE_ID;

    uint256 private constant EXPECTED_INPUTS = 3;

    constructor(IRiscZeroVerifier _verifier, bytes32 _imageId) {
        require(address(_verifier) != address(0), "PolicyVerifier: zero verifier");
        require(_imageId != bytes32(0), "PolicyVerifier: zero imageId");
        RISC0_VERIFIER = _verifier;
        IMAGE_ID = _imageId;
    }

    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external
        view
        returns (bool)
    {
        if (publicInputs.length != EXPECTED_INPUTS) return false;

        bytes memory journal = abi.encodePacked(
            publicInputs[0],
            publicInputs[1],
            publicInputs[2]
        );
        bytes32 journalDigest = sha256(journal);

        try RISC0_VERIFIER.verify(proof, IMAGE_ID, journalDigest) {
            return true;
        } catch {
            return false;
        }
    }
}
